import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { Campaign } from '../../types/campaign';
import { BrandKit } from '../../types/brandKit';
import { GraphicExporter } from './graphicExporter';
import { PdfExporter } from './pdfExporter';
import { generateCampaignFactSheetMarkdown } from '../financials/campaignFactLedger';
import { generateDeterministicPresentationDeck } from '../../features/presentations/services/demoDeckGenerator';

export class MarketingKitZipExporter {
  public static async bundleAndDownloadKit(
    campaign: Campaign,
    brandKit: BrandKit,
    onProgress?: (msg: string, percent: number) => void
  ): Promise<void> {
    const zip = new JSZip();

    // Clean human-friendly folder name
    const isDemo = campaign.tags?.includes('Demo') || campaign.tags?.includes('Fictional') || campaign.id.includes('sample');
    const slug = campaign.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    const folderName = `ZawMarketing-${slug}${isDemo && !slug.includes('demo') ? '-Demo' : ''}`;
    const root = zip.folder(folderName);
    if (!root) throw new Error('Failed to create zip folder');

    onProgress?.('Preparing Strategy & Fact Documents...', 15);

    // 1. Strategy Overview Markdown
    const strat = campaign.strategy;
    const strategyMarkdown = `# ${campaign.name} — Campaign Strategy
Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}
Brand: ${brandKit.companyName}
Status: ${isDemo ? 'FICTIONAL DEMO / SAMPLE FIXTURE' : 'LIVE OFFERING'}

${isDemo ? '> [!NOTE]\n> **DEMO / FICTIONAL SAMPLE**: All strategy angles, quantitative hooks, and market data are illustrative demonstration fixtures. Not a live investment offering or real listing.\n' : ''}

## 1. Executive Angle & Value Proposition
* **Core Angle:** ${strat?.coreAngle || 'N/A'}
* **Primary Objective:** ${strat?.primaryObjective || 'N/A'}
* **Value Proposition:** ${strat?.valueProposition || 'N/A'}

## 2. Target Audience Profile
* **Audience Segment:** ${strat?.targetAudience.name || 'N/A'}
* **Description:** ${strat?.targetAudience.description || 'N/A'}
* **Core Motivations:**
${(strat?.targetAudience.motivations || []).map((m) => `  - ${m}`).join('\n')}
* **Key Pain Points Addressed:**
${(strat?.targetAudience.painPoints || []).map((p) => `  - ${p}`).join('\n')}

## 3. Key Quantitative Hooks
${(strat?.keyHooks || []).map((h, i) => `${i + 1}. ${h}`).join('\n')}

## 4. Supporting Evidence
${(strat?.supportingEvidence || []).map((e, i) => `${i + 1}. ${e}`).join('\n')}

## 5. CTA Strategy
${strat?.ctaStrategy || 'N/A'}

---
*Generated by ZawMarketing Studio for ${brandKit.companyName}*
`;
    root.file('01-Campaign-Strategy.md', strategyMarkdown);

    // 2. All-Platform Copy Markdown
    const copy = campaign.copy;
    const copyMarkdown = `# ${campaign.name} — Multi-Platform Copy Package
Brand: ${brandKit.companyName} (${brandKit.website})
Status: ${isDemo ? 'FICTIONAL DEMO / SAMPLE FIXTURE' : 'LIVE OFFERING'}

================================================================================
APPROVED HEADLINE OPTIONS
================================================================================
${(copy?.headlines || []).map((h, i) => `[Option ${i + 1}] ${h}`).join('\n')}

================================================================================
APPROVED CALL TO ACTION (CTA) OPTIONS
================================================================================
${(copy?.ctas || []).map((c, i) => `[Option ${i + 1}] ${c}`).join('\n')}

================================================================================
1. LINKEDIN / INSTITUTIONAL MEMO POST
================================================================================
HEADLINE: ${copy?.linkedin.headline || ''}

${copy?.linkedin.body || ''}

CTA: ${copy?.linkedin.cta || ''}

================================================================================
2. INSTAGRAM CAPTION & HASHTAGS
================================================================================
HEADLINE: ${copy?.instagram.headline || ''}

${copy?.instagram.body || ''}

CTA: ${copy?.instagram.cta || ''}

HASHTAGS:
${(copy?.instagram.hashtags || []).join(' ')}

================================================================================
3. FACEBOOK POST
================================================================================
HEADLINE: ${copy?.facebook.headline || ''}

${copy?.facebook.body || ''}

CTA: ${copy?.facebook.cta || ''}

================================================================================
4. EMAIL NEWSLETTER & INVESTOR MEMO
================================================================================
SUBJECT LINES:
${(copy?.emailNewsletter.subjectLines || []).map((s, i) => `  [${i + 1}] ${s}`).join('\n')}

PREVIEW TEXT: ${copy?.emailNewsletter.previewText || ''}

BODY (MARKDOWN):
${copy?.emailNewsletter.bodyMarkdown || ''}

CTA BUTTON TEXT: ${copy?.emailNewsletter.ctaButtonText || ''}

---
LEGAL DISCLAIMER:
${isDemo ? 'DEMO / FICTIONAL SAMPLE. ' : ''}${brandKit.requiredDisclaimer}
`;
    root.file('02-Platform-Copy-Package.md', copyMarkdown);

    // 3. Video Reel Script TXT
    const vScript = copy?.videoScript;
    const videoScriptTxt = `================================================================================
60-SECOND SHORT-FORM VIDEO / REEL SCRIPT
Title: ${vScript?.title || campaign.name}
Format: ${vScript?.targetFormat || '9:16 Vertical'}
Duration: ~${vScript?.durationSeconds || 60} Seconds
Status: ${isDemo ? 'FICTIONAL DEMO' : 'LIVE'}
================================================================================

HOOK (0:00 - 0:05):
${vScript?.hook || ''}

SCENE BREAKDOWN:
--------------------------------------------------------------------------------
${(vScript?.scenes || [])
  .map(
    (scene, i) => `SCENE ${i + 1} [${scene.timeframe}]
VISUAL DIRECTION: ${scene.visualDirection}
SPOKEN AUDIO:     "${scene.spokenAudio}"
ON-SCREEN TEXT:   [${scene.onScreenText || 'None'}]
`
  )
  .join('\n--------------------------------------------------------------------------------\n')}

CALL TO ACTION:
${vScript?.callToAction || ''}
`;
    root.file('03-Video-Reel-Script.txt', videoScriptTxt);

    // 4. Campaign Fact Sheet Markdown
    const factSheetMarkdown = generateCampaignFactSheetMarkdown(campaign);
    root.file('04-Campaign-Fact-Sheet.md', factSheetMarkdown);

    // 5. Investment Presentation Deck & Outline
    const presentation = campaign.presentation || generateDeterministicPresentationDeck(campaign, brandKit);
    root.file('05-Investment-Presentation.json', JSON.stringify(presentation, null, 2));

    const presentationOutlineMd = `# ${campaign.name} — Investment Presentation Deck Outline
Brand: ${brandKit.companyName}
Theme Mode: ${presentation.theme.colorScheme}
Total Slides: ${presentation.slides.length}
Status: ${isDemo ? 'FICTIONAL DEMO SAMPLE' : 'LIVE OFFERING'}

${isDemo ? '> [!NOTE]\n> **DEMO / FICTIONAL SAMPLE**: This presentation outline is for platform demonstration purposes.\n' : ''}

## Slide Deck Structure & Narrative
${presentation.slides.map((s, idx) => `
### Slide ${idx + 1}: ${'title' in s && s.title ? s.title : s.type.replace(/_/g, ' ').toUpperCase()} (${s.type})
${'kicker' in s && s.kicker ? `* **Kicker:** ${s.kicker}` : ''}
${'subtitle' in s && s.subtitle ? `* **Subtitle:** ${s.subtitle}` : ''}
${s.speakerNotes ? `* **Speaker Notes:** ${s.speakerNotes}` : ''}
`).join('\n')}

---
*Generated by ZawMarketing Presentation Engine (Bolt-Derived)*
`;
    root.file('05-Investment-Presentation-Outline.md', presentationOutlineMd);

    // 6. README overview
    const readmeTxt = `================================================================================
ZAWMARKETING AUTOMATION STUDIO — MARKETING PACKAGE
Campaign: ${campaign.name}
Brand: ${brandKit.companyName}
Status: ${isDemo ? 'FICTIONAL DEMO SAMPLE' : 'LIVE CAMPAIGN'}
================================================================================

CONTENTS OF THIS PACKAGE:
1. 01-Campaign-Strategy.md  - Executive investment thesis, target audience, and quantitative hooks.
2. 02-Platform-Copy-Package.md - Tailored copy for LinkedIn, Instagram, Facebook, and Email.
3. 03-Video-Reel-Script.txt - 4-scene 60-second vertical video / Reel script with visual cues.
4. 04-Campaign-Fact-Sheet.md - Single source of truth fact ledger and verified underwriting metrics.
5. 05-Investment-Presentation.json - Interactive Bolt Slides investment deck structured JSON.
6. 05-Investment-Presentation-Outline.md - Slide-by-slide presentation outline and speaker notes.
7. graphics/                - 4 social graphics exported at exact target dimensions:
                              * square (1080x1080)
                              * portrait (1080x1350)
                              * story (1080x1920 with safe zones)
                              * landscape (1200x630)
8. flyers/                  - High-resolution printable investment memorandum flyer (PDF).

${isDemo ? 'NOTE: This is a demonstration marketing package containing fictional property data.\n' : ''}
`;
    root.file('README.txt', readmeTxt);

    onProgress?.('Capturing High-Resolution Graphics & Flyers...', 45);

    const graphicsFolder = root.folder('graphics');
    const flyerFolder = root.folder('flyers');

    // Export available DOM canvases
    const formats = ['square', 'portrait', 'story', 'landscape'] as const;
    for (let i = 0; i < formats.length; i++) {
      const fmt = formats[i];
      const elementId = `rendered-design-${fmt}`;
      try {
        const el = document.getElementById(elementId);
        if (el && graphicsFolder) {
          const blob = await GraphicExporter.exportToBlob(el);
          graphicsFolder.file(`${fmt}.png`, blob);
        }
      } catch (err) {
        console.warn(`Could not capture ${fmt} canvas for zip bundle`, err);
      }
    }

    // Export Flyer PDF
    try {
      const letterFlyer = document.getElementById('rendered-design-flyer_letter');
      const a4Flyer = document.getElementById('rendered-design-flyer_a4');
      const flyerEl = letterFlyer || a4Flyer;
      if (flyerEl && flyerFolder) {
        const format = letterFlyer ? 'letter' : 'a4';
        const pdfBlob = await PdfExporter.generatePdfBlob(flyerEl, format);
        flyerFolder.file(`investment-property-flyer-${format}.pdf`, pdfBlob);
      }
    } catch (err) {
      console.warn('Could not capture flyer PDF for zip bundle', err);
    }

    onProgress?.('Compressing Marketing Kit ZIP Archive...', 85);
    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, `${folderName}.zip`);
    onProgress?.('Download Ready!', 100);
  }
}
