import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { Campaign } from '../../types/campaign';
import { BrandKit } from '../../types/brandKit';
import { GraphicExporter } from './graphicExporter';
import { PdfExporter } from './pdfExporter';

export class MarketingKitZipExporter {
  public static async bundleAndDownloadKit(
    campaign: Campaign,
    brandKit: BrandKit,
    onProgress?: (msg: string, percent: number) => void
  ): Promise<void> {
    const zip = new JSZip();
    const folderName = `${campaign.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-marketing-kit`;
    const root = zip.folder(folderName);
    if (!root) throw new Error('Failed to create zip folder');

    onProgress?.('Preparing Strategy & Copy Documents...', 15);

    // 1. Strategy Overview Markdown
    const strat = campaign.strategy;
    const strategyMarkdown = `# ${campaign.name} — Campaign Strategy
Generated: ${new Date().toLocaleDateString()}
Brand: ${brandKit.companyName}

## 1. Executive Angle & Value Proposition
* **Core Angle:** ${strat?.coreAngle || 'N/A'}
* **Primary Objective:** ${strat?.primaryObjective || 'N/A'}
* **Value Proposition:** ${strat?.valueProposition || 'N/A'}

## 2. Target Audience Profile
* **Audience Segment:** ${strat?.targetAudience.name || 'N/A'}
* **Description:** ${strat?.targetAudience.description || 'N/A'}
* **Core Motivations:**
${(strat?.targetAudience.motivations || []).map((m) => `  - ${m}`).join('\n')}
* **Key Pain Points Addressed:**
${(strat?.targetAudience.painPoints || []).map((p) => `  - ${p}`).join('\n')}

## 3. Key Quantitative Hooks
${(strat?.keyHooks || []).map((h, i) => `${i + 1}. ${h}`).join('\n')}

## 4. Supporting Comp Evidence
${(strat?.supportingEvidence || []).map((e, i) => `${i + 1}. ${e}`).join('\n')}

## 5. CTA Strategy
${strat?.ctaStrategy || 'N/A'}

---
*Generated by Zaw Marketing Studio for ${brandKit.companyName}*
`;
    root.file('01-Campaign-Strategy.md', strategyMarkdown);

    // 2. All-Platform Copy Markdown
    const copy = campaign.copy;
    const copyMarkdown = `# ${campaign.name} — Multi-Platform Copy Package
Brand: ${brandKit.companyName} (${brandKit.website})

================================================================================
APPROVED HEADLINE OPTIONS
================================================================================
${(copy?.headlines || []).map((h, i) => `[Option ${i + 1}] ${h}`).join('\n')}

================================================================================
APPROVED CALL TO ACTION (CTA) OPTIONS
================================================================================
${(copy?.ctas || []).map((c, i) => `[Option ${i + 1}] ${c}`).join('\n')}

================================================================================
1. LINKEDIN / INSTITUTIONAL MEMO POST
================================================================================
HEADLINE: ${copy?.linkedin.headline || ''}

${copy?.linkedin.body || ''}

CTA: ${copy?.linkedin.cta || ''}

================================================================================
2. INSTAGRAM CAPTION & HASHTAGS
================================================================================
HEADLINE: ${copy?.instagram.headline || ''}

${copy?.instagram.body || ''}

CTA: ${copy?.instagram.cta || ''}

HASHTAGS:
${(copy?.instagram.hashtags || []).join(' ')}

================================================================================
3. FACEBOOK POST
================================================================================
HEADLINE: ${copy?.facebook.headline || ''}

${copy?.facebook.body || ''}

CTA: ${copy?.facebook.cta || ''}

================================================================================
4. EMAIL NEWSLETTER & INVESTOR MEMO
================================================================================
SUBJECT LINES:
${(copy?.emailNewsletter.subjectLines || []).map((s, i) => `  [${i + 1}] ${s}`).join('\n')}

PREVIEW TEXT: ${copy?.emailNewsletter.previewText || ''}

BODY (MARKDOWN):
${copy?.emailNewsletter.bodyMarkdown || ''}

CTA BUTTON TEXT: ${copy?.emailNewsletter.ctaButtonText || ''}

---
LEGAL DISCLAIMER:
${brandKit.requiredDisclaimer}
`;
    root.file('02-Platform-Copy-Package.md', copyMarkdown);

    // 3. Video Reel Script TXT
    const vScript = copy?.videoScript;
    const videoScriptTxt = `================================================================================
60-SECOND SHORT-FORM VIDEO / REEL SCRIPT
Title: ${vScript?.title || campaign.name}
Format: ${vScript?.targetFormat || '9:16 Vertical'}
Duration: ~${vScript?.durationSeconds || 60} Seconds
================================================================================

HOOK (0:00 - 0:05):
${vScript?.hook || ''}

SCENE BREAKDOWN:
--------------------------------------------------------------------------------
${(vScript?.scenes || [])
  .map(
    (scene, i) => `SCENE ${i + 1} [${scene.timeframe}]
VISUAL DIRECTION: ${scene.visualDirection}
SPOKEN AUDIO:     "${scene.spokenAudio}"
ON-SCREEN TEXT:   [${scene.onScreenText || 'None'}]
`
  )
  .join('\n--------------------------------------------------------------------------------\n')}

CALL TO ACTION:
${vScript?.callToAction || ''}
`;
    root.file('03-Video-Reel-Script.txt', videoScriptTxt);

    onProgress?.('Capturing High-Resolution Graphics & Flyers...', 45);

    const graphicsFolder = root.folder('graphics');
    const flyerFolder = root.folder('flyers');

    // Export available DOM canvases if present
    const formats = ['square', 'portrait', 'story', 'landscape'] as const;
    for (let i = 0; i < formats.length; i++) {
      const fmt = formats[i];
      const elementId = `rendered-design-${fmt}`;
      try {
        const el = document.getElementById(elementId);
        if (el && graphicsFolder) {
          const blob = await GraphicExporter.exportToBlob(el, 2);
          graphicsFolder.file(`${fmt}-1080px.png`, blob);
        }
      } catch (err) {
        console.warn(`Could not capture ${fmt} canvas for zip bundle`, err);
      }
    }

    // Export Flyer PDF
    try {
      const flyerEl = document.getElementById('rendered-design-flyer_letter') || document.getElementById('rendered-design-flyer_a4');
      if (flyerEl && flyerFolder) {
        const pdfBlob = await PdfExporter.generatePdfBlob(flyerEl, 'letter');
        flyerFolder.file('investment-property-flyer.pdf', pdfBlob);
      }
    } catch (err) {
      console.warn('Could not capture flyer PDF for zip bundle', err);
    }

    onProgress?.('Compressing Marketing Kit ZIP Archive...', 85);
    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, `${folderName}.zip`);
    onProgress?.('Download Ready!', 100);
  }
}
